server:
  port: 8002
  servlet:
    context-path: /file

spring:
  application:
    name: file-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
    password: jshkm
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB #Maximum file size
      file-size-threshold: 2KB #Threshold of File Writing to Disk
      max-request-size: 215MB #Maximum request size
    ## Parameters required for file storage
    # All files uploaded through REST APIs will be stored in this directory
upload:
  dir: './my-file/uploads'
